### ISSUE TITLE
esp32_ble_tracker with xiaomi_miflora sensor missing (Battery Level and Illuminance)

### ISSUE THREAD

**Issue by daswars** [OttoWinter/esphomeyaml#161]
Hello. I integrated the xiaomi flora sensors yesterday,
I integrated the xiaomi flora sensors yesterday.
I used 3 esp32 with one flora sensor each.

Here I have the following problems:
The following values are not read -> Battery Level and Illuminance

Furthermore, the nan value is stored as soon as no value is available. And every few minutes it says that the device is not available.
<img width="335" alt="bildschirmfoto 2018-10-11 um 15 48 11" src="https://user-images.githubusercontent.com/7024167/46808696-2fb01b80-cd6d-11e8-8387-4b45d00e55c0.png">
<img width="374" alt="bildschirmfoto 2018-10-11 um 15 48 03" src="https://user-images.githubusercontent.com/7024167/46808714-3c347400-cd6d-11e8-96ac-13480f5dd2be.png">

I would be very happy to help solve the problems.
Thanks

**Comment by OttoWinter** [comment]
Thanks @daswars! Using your logs I was now able to identify the bug: The `illuminance` data field was not a 32-bit integer like the other fields, but a 24-bit integer. See https://github.com/OttoWinter/esphomelib/pull/220

In the logs, I could however not find any broadcasts from the mi flora device about its battery level. I think this is because the xiaomi devices only send out the battery level in BLE mode very seldomly as the battery lasts a long time anyway.
